const data = {
  products: [
    {
      name: 'Something Here1',
      slug: 'something-here1',
      category: 'other',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 10,
      brand: 'Nope',
      rating: 4.1,
      numReviews: 10,
      description: 'Yada yada',
    },
    {
      name: 'Something Here2',
      slug: 'something-here2',
      category: 'other',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nope',
      rating: 4.6,
      numReviews: 10,
      description: 'Yada yada',
    },
    {
      name: 'Something Here3',
      slug: 'something-here3',
      category: 'other',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nope',
      rating: 5,
      numReviews: 10,
      description: 'Yada yada',
    },
    {
      name: 'Something Here4',
      slug: 'something-here4',
      category: 'other',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nope',
      rating: 2.6,
      numReviews: 10,
      description: 'Yada yada',
    },
  ],
};

export default data;
