const data = {
  products: [
    {
      name: 'Something Here',
      slug: 'something-here',
      category: 'other',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nope',
      rating: 4.1,
      numReviews: 10,
      description: 'Yada yada',
    },
    {
      name: 'Something Here',
      slug: 'something-here',
      category: 'other',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nope',
      rating: 4.1,
      numReviews: 10,
      description: 'Yada yada',
    },
    {
      name: 'Something Here',
      slug: 'something-here',
      category: 'other',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nope',
      rating: 4.1,
      numReviews: 10,
      description: 'Yada yada',
    },
    {
      name: 'Something Here',
      slug: 'something-here',
      category: 'other',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nope',
      rating: 4.1,
      numReviews: 10,
      description: 'Yada yada',
    },
  ],
};

export default data;
